server:
  port: 1024

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/last_task_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: false

